# Run by default on lowest supported Python version
image: python:3.8

include:
  - template: Jobs/SAST.gitlab-ci.yml

before_script:
  - pip install tox

stages:
  - style
  - build
  - test
  - coverage
  - examples
  - deploy

# style
style:
  stage: style
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - apt update && apt install -y --no-install-recommends git
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure
  tags:
    - docker

# build
build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - docker

.python_tox_matrix:
  image: python:${VERSION}
  script:
    - tox -vv
  parallel:
    matrix:
      - VERSION: ["3.8", "3.9", "3.10", "3.11"]
  tags:
    - docker

# test
test:linux:
  stage: test
  extends: .python_tox_matrix
  variables:
    TOXENV: py

# run examples (only for tags)
examples:linux:
  stage: examples
  extends: .python_tox_matrix
  variables:
    TOXENV: examples
  only:
    - tags

# coverage
coverage:
  stage: coverage
  script:
    - tox -vv
    - pip install codecov
    - codecov --token=$CODECOV_TOKEN
  variables:
    TOXENV: coverage
  tags:
    - docker

# deploy
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - pip install twine
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
    # Only deploy refs that start with "2."
    - /^2\..*$/
  except:
    # If a branch happens to start with "2.", skip it as we only want to
    # deploy tags.
    - branches
  tags:
    - docker
